### ISSUE TITLE
Nodes files were not copied to the destination folder

### ISSUE THREAD

**Issue by robosina** [qt/qtquickeffectmaker#1]
Have you ever encountered the problem of nodes not being copied to the destination during the `cmake` step? I have encountered the issue and I have forked the branch and fixed it on my system, but I was wondering what I might be doing wrong here or if this fix is worth a pull request. (_I am using Qt6.4.1 and the specified branch as well. Now the images load correctly, but the shaders or nodes are empty._)

# here is the things/errors before my little fixup:

### CMake Logs

```cmake
Nodes path: ./qml/QtQuickEffectMaker/defaultnodes
```

And 

### runtime blames

```
/home/saeed/Qt/qtquickeffectmaker/cmake-build-debug/bin/qqem
Can't read image: file:///home/saeed/Qt/qtquickeffectmaker/cmake-build-debug/bin/defaultnodes/images/qt_logo_green_rgb.png
Can't read image: file:///home/saeed/Qt/qtquickeffectmaker/cmake-build-debug/bin/defaultnodes/images/quit_logo.png
Can't read image: file:///home/saeed/Qt/qtquickeffectmaker/cmake-build-debug/bin/defaultnodes/images/whitecircle.png
Can't read image: file:///home/saeed/Qt/qtquickeffectmaker/cmake-build-debug/bin/defaultnodes/images/blackcircle.png
```

**Comment by cmaureir** [comment]
Hey @robosina thanks for the report. Qt repositories on Github are only mirrors because the development is done in Gerrit: https://codereview.qt-project.org
Also, all the bug reports are handle in: https://bugreports.qt.io

You can find more information in https://wiki.qt.io/Reporting_Bugs 

Cheers
